
    public CompletionException(Throwable cause) {
        super(cause);
    }
}
